platform :ios,'9.0'

source 'https://github.com/localz/Spotz-iOS-Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

project 'SampleLocalzAttendantApp-ObjC'
target 'SampleLocalzAttendantApp-ObjC' do
    pod 'LocalzAttendantSDK'
end

